import { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';

interface WeddingData {
  couple: {
    name: string;
    email: string;
    partnerName: string;
  };
  wedding: {
    date: string;
    guestCount: number;
    style: 'intimate' | 'classic' | 'luxury';
    region: 'lisboa' | 'porto' | 'center' | 'south' | 'islands';
    season: 'spring' | 'summer' | 'autumn' | 'winter';
    priorities: string[];
    estimatedBudget: number;
  };
  isSetupComplete: boolean;
}

interface WeddingContextType {
  weddingData: WeddingData | null;
  setWeddingData: (data: WeddingData) => void;
  clearWeddingData: () => void;
  saveToCloud: (data: WeddingData) => Promise<void>;
  loadFromCloud: () => Promise<void>;
}

const WeddingContext = createContext<WeddingContextType | undefined>(undefined);

export const useWeddingData = () => {
  const context = useContext(WeddingContext);
  if (!context) {
    throw new Error('useWeddingData must be used within a WeddingProvider');
  }
  return context;
};

interface WeddingProviderProps {
  children: ReactNode;
}

export const WeddingProvider = ({ children }: WeddingProviderProps) => {
  const { user } = useAuth();
  const [weddingData, setWeddingDataState] = useState<WeddingData | null>(() => {
    // Try to load from localStorage on initialization (fallback)
    const stored = localStorage.getItem('weddingData');
    return stored ? JSON.parse(stored) : null;
  });

  // Load data from cloud when user logs in
  useEffect(() => {
    if (user) {
      loadFromCloud();
    }
  }, [user]);

  const setWeddingData = (data: WeddingData) => {
    setWeddingDataState(data);
    localStorage.setItem('weddingData', JSON.stringify(data));
    // Also save to cloud if user is logged in
    if (user) {
      saveToCloud(data);
    }
  };

  const clearWeddingData = () => {
    setWeddingDataState(null);
    localStorage.removeItem('weddingData');
    // Also clear from cloud if user is logged in
    if (user) {
      clearFromCloud();
    }
  };

  const saveToCloud = async (data: WeddingData) => {
    if (!user) return;

    try {
      // Check if wedding data already exists
      const { data: existing } = await supabase
        .from('wedding_data')
        .select('id, event_code')
        .eq('user_id', user.id)
        .maybeSingle();

      if (existing) {
        // Update existing record
        const { error } = await supabase
          .from('wedding_data')
          .update({
            couple_name: data.couple.name,
            partner_name: data.couple.partnerName,
            wedding_date: data.wedding.date,
            guest_count: data.wedding.guestCount,
            style: data.wedding.style,
            region: data.wedding.region,
            season: data.wedding.season,
            priorities: data.wedding.priorities,
            estimated_budget: data.wedding.estimatedBudget,
            is_setup_complete: data.isSetupComplete
          })
          .eq('user_id', user.id);

        if (error) {
          console.error('Error updating cloud data:', error);
        }
      } else {
        // Insert new record (event_code will be generated by DB)
        const { error } = await supabase
          .from('wedding_data')
          .insert([{
            user_id: user.id,
            couple_name: data.couple.name,
            partner_name: data.couple.partnerName,
            wedding_date: data.wedding.date,
            guest_count: data.wedding.guestCount,
            style: data.wedding.style,
            region: data.wedding.region,
            season: data.wedding.season,
            priorities: data.wedding.priorities,
            estimated_budget: data.wedding.estimatedBudget,
            is_setup_complete: data.isSetupComplete,
            event_code: ''  // Will be generated by the database
          }]);

        if (error) {
          console.error('Error creating cloud data:', error);
        }
      }
    } catch (error) {
      console.error('Error saving to cloud:', error);
    }
  };

  const loadFromCloud = async () => {
    if (!user) return;

    try {
      console.log('[WeddingContext] Loading wedding data for user:', user.id);
      
      // First try to find wedding where user is the owner
      let { data, error } = await supabase
        .from('wedding_data')
        .select('*')
        .eq('user_id', user.id)
        .maybeSingle();

      // If not owner, check if user is a collaborator
      if (!data) {
        console.log('[WeddingContext] User is not owner, checking collaborations...');
        const { data: collabData, error: collabError } = await supabase
          .from('wedding_collaborators')
          .select('wedding_id')
          .eq('user_id', user.id)
          .maybeSingle();

        if (collabError) {
          console.error('[WeddingContext] Error checking collaborations:', collabError);
          return;
        }

        if (collabData) {
          console.log('[WeddingContext] User is collaborator, loading wedding:', collabData.wedding_id);
          // Load the wedding data they're collaborating on
          const { data: weddingData, error: weddingError } = await supabase
            .from('wedding_data')
            .select('*')
            .eq('id', collabData.wedding_id)
            .single();

          if (weddingError) {
            console.error('[WeddingContext] Error loading wedding data:', weddingError);
            return;
          }

          data = weddingData;
        } else {
          console.log('[WeddingContext] User has no wedding data');
        }
      } else {
        console.log('[WeddingContext] User is owner of wedding:', data.id);
      }

      if (error && error.code !== 'PGRST116') {
        console.error('[WeddingContext] Error loading from cloud:', error);
        return;
      }

      if (data) {
        console.log('[WeddingContext] Wedding data loaded successfully');
        const weddingData: WeddingData = {
          couple: {
            name: data.couple_name || '',
            email: user.email || '',
            partnerName: data.partner_name || ''
          },
          wedding: {
            date: data.wedding_date || '',
            guestCount: data.guest_count || 50,
            style: (data.style as 'intimate' | 'classic' | 'luxury') || 'classic',
            region: (data.region as 'lisboa' | 'porto' | 'center' | 'south' | 'islands') || 'lisboa',
            season: (data.season as 'spring' | 'summer' | 'autumn' | 'winter') || 'spring',
            priorities: data.priorities || [],
            estimatedBudget: data.estimated_budget || 0
          },
          isSetupComplete: data.is_setup_complete || false
        };
        setWeddingDataState(weddingData);
        localStorage.setItem('weddingData', JSON.stringify(weddingData));
      }
    } catch (error) {
      console.error('[WeddingContext] Error loading from cloud:', error);
    }
  };

  const clearFromCloud = async () => {
    if (!user) return;

    try {
      const { error } = await supabase
        .from('wedding_data')
        .delete()
        .eq('user_id', user.id);

      if (error) {
        console.error('Error clearing from cloud:', error);
      }
    } catch (error) {
      console.error('Error clearing from cloud:', error);
    }
  };

  return (
    <WeddingContext.Provider value={{ 
      weddingData, 
      setWeddingData, 
      clearWeddingData, 
      saveToCloud, 
      loadFromCloud 
    }}>
      {children}
    </WeddingContext.Provider>
  );
};